### ISSUE TITLE
Update SDK with latest spec changes

### ISSUE THREAD

**Issue by toddbaert** [open-feature/node-sdk#23]
Add:

- updated error behavior (client creation should never throw)
- structure support in context: https://github.com/open-feature/spec/blob/main/specification/evaluation-context/evaluation-context.md#requirement-32
- tests for above

**Comment by weyert** [comment]
I am not sure what the expected error behaviour is supposed to be. It's not really clear for me from reading the providers markdown file

**Comment by toddbaert** [comment]
> I am not sure what the expected error behaviour is supposed to be. It's not really clear for me from reading the providers markdown file

https://github.com/open-feature/spec/blob/main/specification/flag-evaluation/flag-evaluation.md#requirement-116

This is the change. I'm not sure if there's much we can do to meaningfully test this, it's more of a design requirement.

I'll think about it a bit, but the other thing that needs to happen is some of the numbering for the tests have to be updated. You can leave that for me. I think you did your part with the JSON support.
