### ISSUE TITLE
Auto-merge Dependabot Dev Dependency Upgrades

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/node-sdk#74]
Dependabot is opening PRs when it detects that an upgrade is available. This is great to keep packages up-to-date but it has become a maintenance issue. To alleviate this burden, a GitHub action should be configured to auto-merge minor/patch dev dependencies that pass the CI process.

**Comment by thomaspoignant** [comment]
I have tried https://github.com/apps/kodiakhq and it works well, you can decide what to merge (only minor or major also).
You have an example of the configuration [here](https://github.com/thomaspoignant/go-feature-flag/blob/main/.kodiak.toml).

**Comment by beeme1mr** [comment]
Thanks @thomaspoignant, I'll check it out.

**Comment by beeme1mr** [comment]
Worked great! Thanks for the tip @thomaspoignant .

**Comment by thomaspoignant** [comment]
> Worked great! Thanks for the tip @thomaspoignant .

Glad you liked it 👍
